#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

app=zarafa

# Retrieve arguments
path=$2
domain=$1

# Check distribution. Only Debian 7 & 8 are supported.
read -d . VERSION < /etc/debian_version
case "$VERSION" in
	7) DOWNLOADURL=http://download.zarafa.com/zarafa/drupal/download_platform.php?platform=final/7.2/7.2.1-51838/zcp-7.2.1-51838-debian-7.0-x86_64-supported.tar.gz
	DOWNLOADWEBAPPURL=http://download.zarafa.com/community/beta/WebApp/2.1.2/RC2/debian-7.0/;;
	8) DOWNLOADURL=http://download.zarafa.com/zarafa/drupal/download_platform.php?platform=final/7.2/7.2.1-51838/zcp-7.2.1-51838-debian-8.0-x86_64-supported.tar.gz
	DOWNLOADWEBAPPURL=http://download.zarafa.com/community/beta/WebApp/2.1.2/RC2/debian-8.0/;;
	*) echo "Your Distribution is not supported by this app!"; exit 1 ;;
esac

# check architecture. Only 64bit is supported.
if [ $(uname -m) != "x86_64" ] ; then
	echo "Your architecture is not supported by this app!"
	exit 1
fi 

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app \
	|| (echo "Path not available: $path" && exit 1)

# Download and install zarafa packages
createrepo(){
	DOWNLOADURL=$1
	DOWNLOADWEBAPPURL=$2
	mkdir -p /home/admin/packages \
	&& wget --no-check-certificate --quiet \
	$DOWNLOADURL -O- | tar xz -C /home/admin/packages --strip-components=1
	cd /home/admin/packages
	wget --quiet -p -r -nc -nd -l 1 -e robots=off -A deb --no-check-certificate $DOWNLOADWEBAPPURL
	apt-ftparchive packages . | gzip -9c > Packages.gz \
	&& sudo sh -c 'echo "deb file:/home/admin/packages ./" > /etc/apt/sources.list.d/zarafa.list'
cd -
}
createrepo $DOWNLOADURL $DOWNLOADWEBAPPURL
sudo apt-get update && RUNLEVEL=1 sudo apt-get install --allow-unauthenticated --assume-yes \
zarafa-server zarafa-spooler zarafa-dagent zarafa-webapp zarafa-utils

# Define database user and create password
db_user=zarafa
db_pwd=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{24\}\).*/\1/p')

#Initialize database and store mysql password for upgrade
sudo yunohost app initdb $db_user -p $db_pwd
sudo yunohost app setting $app mysqlpwd -v $db_pwd

# Set mysql password in server.cfg
sed -i "s@mysqlpwd@$db_pwd@g" ../conf/server.cfg
sed -i "s@servercrt@/etc/yunohost/certs/$domain/crt.pem@g" ../conf/server.cfg
sed -i "s@serverca@/etc/yunohost/certs/$domain/ca.pem@g" ../conf/server.cfg
sudo cp ../conf/server.cfg /etc/zarafa/
sudo cp ../conf/ldap.cfg /etc/zarafa/

final_path=/usr/share/zarafa-webapp

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf

# Adapt PHP-MAPI
sudo ln -s /etc/php5/apache2/conf.d/zarafa.ini /etc/php5/fpm/conf.d/50-zarafa.ini

# Copy nginx.conf to domain subfolder
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Restart webserver
sudo service nginx reload
sudo yunohost app ssowatconf
sudo service php5-fpm restart
sudo service zarafa-server start

# Create public store
sudo zarafa-admin -s
