#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

app=zarafa

# Retrieve arguments
path=$1

# Check domain/path availability
sudo yunohost app checkurl $path -a $app \
	|| (echo "Path not available: $path" && exit 1)

# TODO download and install zarafa packages

# TODO set mysql password in server.cfg

# TODO set ldap settign in ldap.cfg

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf

# If your app use a MySQL database you can use these lines to bootstrap
# a database, an associated user and save the password in app settings
db_pwd=$(openssl rand -hex 15)
sudo yunohost app initdb $app -p $db_pwd
sudo yunohost app setting $app mysqlpwd -v $db_pwd

# Copy source files
# TODO change location of WebApp to the value given in $path
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$app.conf

# Restart webserver
sudo service nginx reload
sudo yunohost app ssowatconf
