#!/bin/bash

app=zarafa

# Retrieve arguments
db=zarafa
db_user=zarafa

# TODO remove all zarafa packages

# Remove configuration files
sudo rm -f /etc/nginx/conf.d/$app.conf

# If a database is used, remove it
db_pwd=$(sudo cat /etc/yunohost/mysql)
mysql -u root -p$db_pwd -e "DROP DATABASE $db ; DROP USER $db_user@localhost ;"

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf
